### ISSUE TITLE
[BUG] SSO failure: unable to retrieve a token

### ISSUE THREAD

**Issue by danigian** [microsoft/promptflow#973] opened 2023-10-31 10:52 UTC
**Describe the bug**
"SSO failure: unable to retrieve a token" while submitting a run to Azure ML with the PFClient.
A custom runtime is being used mapped to a Compute Instance assigned to a Managed Identity.
This stopped working after couple of runs.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b8
 - Operating System: Debian 11
 - Python Version using `python --version`: 3.11.6

**Additional context**
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 58, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 416, in submit_bulk_run
    return self.caller.bulk_runs.submit_bulk_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/_restclient/flow/operations/_bulk_runs_operations.py", line [37](REDACTED/actions/runs/6705342707/job/18219563241#step:6:38)0, in submit_bulk_run
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: (UserError) Prepare data failed. Unexpected content type "text/plain; charset=utf-8"
Content: SSO failure: unable to retrieve a token. Error 
Code: UserError
Message: Prepare data failed. Unexpected content type "text/plain; charset=utf-8"
Content: SSO failure: unable to retrieve a token. Error
```

**Comment by danigian** [comment] 2023-11-01 14:04
Reopening the issue, as we are still having the above mentioned problem. Another similar stacktrace below:

```
Traceback (most recent call last):
  File "/home/runner/work/REDACTED/src/data_retrieval/flows/data_retrieval_eval/eval", line 52, in <module>
    main_result = client.run(flow=flows_directory / 'data_retrieval_main',
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/_pf_client.py", line 248, in run
    return self.runs.create_or_update(run=run, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 226, in create_or_update
    self._service_caller.submit_bulk_run(
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 60, in wrapper
    raise FlowRequestException(
promptflow.azure._restclient.flow_service_caller.FlowRequestException: Calling submit_bulk_run failed with request id: 2ad72472-9f8b-4a00-9316-b[56](https://github.com/REDACTED/actions/runs/6718373273/job/18257971030#step:6:57)75a10a[57](https://github.com/REDACTED/actions/runs/6718373273/job/18257971030#step:6:58)1 
Status code: 500 
Reason: Prepare data failed. DefaultAzureCredential failed to retrieve a token from the included credentials 
Error message: (ServiceError) Prepare data failed. DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: SSO failure: unable to retrieve a token. Error 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Code: ServiceError
Message: Prepare data failed. DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: SSO failure: unable to retrieve a token. Error 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Comment by D-W-** [comment] 2023-11-07 06:02
Hi @danigian , this seems like a runtime auth issue. Could you try submit flow run in UI with same runtime and check if the error repros? We'll keep investigate the root cause of the issue.

**Comment by danigian** [comment] 2023-11-07 14:36
@D-W- unfortunately I can't submit the flow in UI as this runtime is created and running on a compute instance assigned to a Managed Identity.

In addition, since last thursday, I am not able anymore to create new custom runtimes on this instance (they are stuck in a  perennial "Runtime creation in progress" status)

Is the usage of compute instances assigned to managed identities a supported scenario? (I am not speaking about compute instances assigned to user principal with a managed identity associated to the node)

**Comment by D-W-** [comment] 2023-11-08 03:21
Hi @danigian , this issue is compute instance related, we are following up with related compute instance team, will get back to you when we got replies.

**Comment by D-W-** [comment] 2023-11-13 03:08
Hi @danigian , as offline synced, we'll close this issue since it's fixed by assigning correct identity.

**Closed by D-W-** 2023-11-13 03:08 UTC
Labels: bug
