### ISSUE TITLE
[BUG] Testing streaming tool with VS Code extension does not serialize chat history correctly

### ISSUE THREAD

**Issue by martinmoldrup** [microsoft/promptflow#3645] opened 2024-08-13 11:07 UTC
**Describe the bug**
If a flow is using streaming and the VS Code Extension to  "Run it with interactive mode (text only)" is used to test it, it does not serialize properly. It serializes the answer as "<promptflow.tracing._trace.TracedIterator object at 0x0000022B85534520>" into the prompt instead of the string.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Make a flow that uses a custom tool that streams the answer for the final completion. Make sure it is running in stream mode and the tool is returning a TracedIterator
2. Use the VS Code Extension for "Run it with interactive mode (text only)" and create a short chat history. 
3. The prompt chat history is not serialized correctly when you check it in the trace details.

**Expected behavior**
The answer from the assistant should be serialized into the prompt. 

**Screenshots**
See screenshot of issue
![image](https://github.com/user-attachments/assets/ad6c8627-4993-48c1-976e-574444ea96a9)

**Running Information(please complete the following information):**
 - Promptflow Package Version:
 - {
  "promptflow": "1.14.0",
  "promptflow-azure": "1.14.0",
  "promptflow-core": "1.14.0",
  "promptflow-devkit": "1.14.0",
  "promptflow-tracing": "1.14.0"
}
 - Operating System: Windows 11
 - Python Version:  3.9.18
 - Prompt flow Extension: v1.21.133218292 (pre-release)

**Additional context**
None

**Comment by khoapip** [comment] 2024-08-15 08:22
I got this bug too, but for --interactive mode. It seems that in some case, the output doesn't get Serialized and return TraceIterator, so chat_history won't be able to read the result.

How To Reproduce the bug
Run the main example on README:  pf flow test --flow ./my_chatbot --interactive
The bot won't be able to recall any conversation, because chat_history output are TraceIterator

![image](https://github.com/user-attachments/assets/104b45d2-2637-42fd-9e8e-c4d4eaf1df29)

**Comment by khoapip** [comment] 2024-08-15 09:47
> I got this bug too, but for --interactive mode. It seems that in some case, the output doesn't get Serialized and return TraceIterator, so chat_history won't be able to read the result.
> 
> How To Reproduce the bug Run the main example on README: pf flow test --flow ./my_chatbot --interactive The bot won't be able to recall any conversation, because chat_history output are TraceIterator
> 
> ![image](https://private-user-images.githubusercontent.com/26734897/358164099-104b45d2-2637-42fd-9e8e-c4d4eaf1df29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzNzAsIm5iZiI6MTcyMzcxNTA3MCwicGF0aCI6Ii8yNjczNDg5Ny8zNTgxNjQwOTktMTA0YjQ1ZDItMjYzNy00MmZkLTllOGUtYzRkNGVhZjFkZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Yzg5MmE2MDJlMjQzNjFjOTkzN2RjMzYwNjVmOWRiYWNmZGQ3ODg1NjdiNTlmZGQ1OWY2ZDZlYjI5Yzg2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVTC7H3KpZqL0wpIuic_nghHlirL-B11fJFCPjzQ7Zw)

I fix it in interactive mode by changing resolve_generator in `src/promptflow-devkit/promptflow/_sdk/_orchestrator/utils.py`. But I think the webUI also call resolve_generator, so changing it might fix both

**Comment by oddrationale** [comment] 2024-08-21 18:12
> I fix it in interactive mode by changing resolve_generator in `src/promptflow-devkit/promptflow/_sdk/_orchestrator/utils.py` to resolve Iterator too. I think the webUI also call resolve_generator, so changing it might fix both

Thanks! This fixed it for me, too! Hopefully your PR gets merged in the next version!

**Closed** 2024-09-29 21:32 UTC
Labels: bug, vscode extension, no-recent-activity

**Comment by pback-ores** [comment] 2025-03-24 14:19
This issue raised its head on me in 1.17.2, please reopen.

![Image](https://github.com/user-attachments/assets/bcd27a40-e818-4bfa-8e23-caf38597bdb4)
