### ISSUE TITLE
[BUG] ToolLoadError - Failed to load package tool 'Vector Index Lookup': (ModuleNotFoundError) No module named 'promptflow.runtime'

### ISSUE THREAD

**Issue by tpatnala** [microsoft/promptflow#1010] opened 2023-11-06 14:52 UTC
**Issue Faced**
I have a flow created in my azure promptflow, and was trying to setup and run promptflow from VS but getting the following error.

Flow test failed with ResolveToolError: Tool load failed in 'search_question_from_indexed_docs': (ToolLoadError) Failed to load package tool 'Vector Index Lookup': (ModuleNotFoundError) No module named 'promptflow.runtime'.

<img width="921" alt="image" src="https://github.com/microsoft/promptflow/assets/142984515/1ca6bc6a-ad90-4f2a-a43c-0c13863a0827">

**Steps to reproduce**
1. Download all the files from the azure for any of the pf.
2. Open the folder in VS.
3. Install the extension - Prompt flow for VS Code  v1.3.1.
4. Once installed, open flow.dag.yml file and click on Visual Editor.
5. Make sure you have all the connections working.
6. Click on Run All.

**Expected behavior**
1. I want all the nodes from the configuration file to execute successfully, so that I can chat and do further development.
2. I know i could do it in azure but wanted this for automated deployment and for building docker images.

**Running Information(please complete the following information):**
 - Promptflow Package Version : 0.1.0b7.post1
 - Operating System: Windows 11
 - Python Version using `python --version`: [e.g. python==3.11]

**Comment by TiFaBl** [comment] 2023-11-14 10:34
Hi @dans-msft , is there a timeline on this? Since RAG is an essential part of most LLM apps, not being able to work with the vector index lookup during local development is a pretty big problem.

**Comment by TiFaBl** [comment] 2023-11-17 09:18
This seems to be a duplicate of https://github.com/microsoft/promptflow/issues/788

There appears to be a solution proposal in that issue for more than 3 weeks - which either makes hope to get a fix soon or is a bad sign regarding the low priority of PromptFlow tools working locally.

**Comment by dans-msft** [comment] 2023-11-20 19:26
Update added to #788

**Closed** 2023-12-28 21:33 UTC
Labels: bug, no-recent-activity
