### ISSUE TITLE
[BUG] Issue in Batch Run Settings 

### ISSUE THREAD

**Issue by Kevinlee49** [microsoft/promptflow#2297] opened 2024-03-11 19:30 UTC
While attempting to upload the data from a CSV file, I noticed that the input mapping and real data are not appearing. However, when using a JSONL file, they are visible, as shown in the screenshots below. Could you please verify if the CSV file is being correctly uploaded in the batch run settings?

<img width="1482" alt="2024-03-11_15-22-18" src="https://github.com/microsoft/promptflow/assets/86863395/b1977926-4320-4e33-a9e5-2e967445eebe">
<img width="1207" alt="2024-03-11_15-23-05" src="https://github.com/microsoft/promptflow/assets/86863395/3fcdfa8a-958e-42bf-b840-49b742889871">

**Comment by brynn-code** [comment] 2024-03-12 02:40
I've assigned to expert responsible for promptflow in Azure workspace. Besides, github issue mostly track the open source version promptflow, for things related to promptflow in Azure workspace, refer to this [guide](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience) to open the OCV(one customer voice) specific for azure.

**Comment by Kevinlee49** [comment] 2024-03-12 03:33
@brynn-code Thank you for reply, I already left some reports 2-3 weeks ago in OCV for prompt flow in Azure portal. However, no one replied my problems until now. That's why I keep leaving issues here.

**Comment by brynn-code** [comment] 2024-03-12 03:41
Got it, thanks for the feedback, I'll report this back to our team.

**Comment by Kevinlee49** [comment] 2024-03-12 03:43
@brynn-code Thank you, then do I need to leave these issues again through OCV?

**Comment by brynn-code** [comment] 2024-03-12 03:54
Sorry for the bad experience, I'm not sure why we didn't see the OCV during daily tracking, checking with PM for the OCV problem. For this issue, I'll include our expert to investigate your problem, and for #2300, we may need more detail information, I'll check the issue again and reply to that issue for things we need for further investigation.

**Comment by brynn-code** [comment] 2024-03-12 03:55
We are checking with our PM at the same time, if we find the untriaged OCV issue, we will keep tracking your problem with that.

**Comment by Kevinlee49** [comment] 2024-03-12 03:57
@brynn-code No worries, the issue that I left 2 weeks ago is now under investigation with @Adarsh-Ramanathan. And "https://github.com/microsoft/promptflow/issues/2300, we may need more detail information" - please let me know if you need more detail information.

**Comment by brynn-code** [comment] 2024-03-12 04:00
Is that OCV report the same bug with this one, the batch run setting issue?

**Comment by brynn-code** [comment] 2024-03-12 05:40
I see, our partner team responsible for the index lookup issue and ocv triaged to them.

**Comment by brynn-code** [comment] 2024-03-12 05:49
Just confirmed with our teammates, we'd like you convert the two issue to ocvs, because we could get some workspace information from the ocv, which is important for log querying and not proper to share through github. The two issues should be triaged to our team directly instead of our partner team,  I'll keep the two issue open, until your new ocv got tracked and triaged.

**Comment by linningmii** [comment] 2024-03-12 07:43
@Kevinlee49 could you please help provide a small sample of your CSV and ensure it does not work in our datapreview UI now?

As I know our data preview feature doesn't support **CSV with multiline content cell** because of performance concerns, for such a scenario we recommend using JSONL instead.

**Comment by Kevinlee49** [comment] 2024-03-12 14:41
@linningmii Here it is. There's not only issue in displaying data preview, but also I can't select value in input mapping. That's why I was thinking it is a bug.
<img width="104" alt="2024-03-12_10-38-59" src="https://github.com/microsoft/promptflow/assets/86863395/52a9abc7-d2ab-4cd3-962a-5c83febfc252">
<img width="1207" alt="2024-03-11_15-23-05" src="https://github.com/microsoft/promptflow/assets/86863395/a7ac5f48-ed49-4fc6-aeab-f1f2abcee2ff">

**Comment by linningmii** [comment] 2024-03-13 03:08
Hi @Kevinlee49 

Based on your screenshot I tried to create a [CSV file](https://github.com/microsoft/promptflow/files/14581339/test.csv)  and confirm it's worked.
![image](https://github.com/microsoft/promptflow/assets/14858674/0ead923b-9401-412c-99c9-84c0dffb124f)

**Could you share a small sample of your original file** instead of a screenshot? Then I can use your sample file to test and to confirm whether it includes CSV multiline syntax or not.

And there's a mistake in my last comment, the Azure machine learning studio doesn't support CSV multiline syntax, neither parse nor data preview, you can't preview it because we can't parse it.

**Comment by Kevinlee49** [comment] 2024-03-13 05:35
@linningmii Hello, I just checked that my previous csv file was invalid, I checked with the other csv file and it worked. Thank you!

**Closed** 2024-03-13 05:35 UTC
Labels: bug
