### ISSUE TITLE
[BUG] [VSCode Extension] Adding functions to an LLM tool, adds the same functions to all LLM tools in flow.

### ISSUE THREAD

**Issue by roel4ez** [microsoft/promptflow#1867] opened 2024-01-26 16:07 UTC
**Describe the bug**
The LLM tool provides a button to add functions:
![image](https://github.com/microsoft/promptflow/assets/1822123/f4aaa9d0-273b-429a-b822-7301e6324e57)

When clicking that button, a new json file opens and a (list of) functions can be added. 

When saving/closing this file:
**EXPECTED**: the functions array is added to the one that was selected.
**ACTUAL**: it is added to _all_ nodes of type LLM in the flow.

SCREENSHOTS:
Added to the selected node:
![image](https://github.com/microsoft/promptflow/assets/1822123/5c9f60fc-4afb-4cf1-b07e-11389b9afd1a)

Added to another LLM node:
![image](https://github.com/microsoft/promptflow/assets/1822123/d5acb0b1-7202-4df5-9054-ab0131f1c31a)

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/1822123/9f9a4c73-8615-4772-9d2a-50437cb7ff1c)

**Environment Information**
 - Promptflow Package Version: [1.1.0]
 - Operating System: [DevContainer based on `mcr.microsoft.com/devcontainers/python:3.11`]
 - Python Version: [python==3.11.7]
 - VS Code version: [1.86.0-insiders]
 - Prompt Flow extension version: [1.9.2]

**Comment by chenyugithub365** [comment] 2024-01-28 03:35
I have also encountered similar problems. Sometimes it happens. You can temporarily bypass this issue by directly editing the YAML file.

**Comment by Joouis** [comment] 2024-01-31 09:52
@roel4ez @chenyugithub365 Thanks for your reports. We've figured out the root cause and it should be fixed in next release.

**Closed** 2024-03-05 06:13 UTC
Labels: bug, no-recent-activity
