### ISSUE TITLE
[BUG] when running Langchain AgentExecutor, TypeError occurs - 'generator' object does not support the context manager protocol

### ISSUE THREAD

**Issue by hyeonje-cho** [microsoft/promptflow#3079] opened 2024-04-30 05:30 UTC
**Describe the bug**
When running the langchain AgentExecutor in a Python tool, a TypeError occurs. The function runs fine in environments without the Python tool decorator

**How To Reproduce the bug**
Here is my code. 
```
from promptflow.core import tool
from dotenv import load_dotenv, find_dotenv
from langchain_openai import AzureChatOpenAI
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain_community.tools import DuckDuckGoSearchRun
from promptflow.connections import AzureOpenAIConnection
from langchain import hub


@tool
def my_python_tool(question: str, openai_connect: AzureOpenAIConnection) -> str:
    load_dotenv(find_dotenv(), override=True)
    llm = AzureChatOpenAI(
        azure_deployment="gpt-35-turbo-16k",  # gpt-35-turbo-16k or gpt-4-32k
        openai_api_key=openai_connect.api_key,
        azure_endpoint=openai_connect.api_base,
        openai_api_type=openai_connect.api_type,
        openai_api_version=openai_connect.api_version,
    )
    search = DuckDuckGoSearchRun()
    tools = [search]
    prompt = hub.pull("hwchase17/openai-tools-agent")
    agent = create_tool_calling_agent(llm, tools, prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=False)
    result = agent_executor.invoke({"input": question})

    return result["output"]
```

**Expected behavior**
Return agent_executor's output

**Screenshots**

![image](https://github.com/microsoft/promptflow/assets/166415789/d8c6d745-d93e-43c9-926c-b2f8cc9c8094)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`:
   - {
    "promptflow": "1.9.0",
    "promptflow-core": "1.9.0",
    "promptflow-devkit": "1.9.0",
    "promptflow-tracing": "1.9.0"
  }
 - Operating System: Windows 11
 - Python Version using `python --version`: python==3.12.3 

**Additional context**

**Comment by guming-learning** [comment] 2024-05-09 02:47
Root cause:
langchain-openai wrap stream code in context manager block in [this PR](https://github.com/langchain-ai/langchain/pull/18013/files), which is released in [langchain-openai 0.1.2](https://pypi.org/project/langchain-openai/0.1.2/) on Apr 10, 2024. Which introduces such change:
```
with self.client.create(messages=message_dicts, **params) as response:
    ...
```

However, promptflow wraps the generator output of OpenAI api for tracing, and the wrapped generator does not implement `__enter__` and `__exit__` function, thus causes the error.

We will change the wrapper to align with the original context manager behavior.

**Closed** 2024-05-17 07:02 UTC
Labels: bug

**Comment by gurvinder-dhillon** [comment] 2024-06-06 09:03
Is this released ? I am still seeing the same error.
TypeError: 'generator' object does not support the context manager protocol

promptflow                               1.11.0
promptflow-azure                         1.11.0
promptflow-core                          1.11.0
promptflow-devkit                        1.11.0
promptflow-tools                         1.4.0
promptflow-tracing                       1.11.0
langchain-openai                         0.1.7

**Comment by guming-learning** [comment] 2024-06-12 03:47
> Is this released ? I am still seeing the same error. TypeError: 'generator' object does not support the context manager protocol
> 
> promptflow 1.11.0 promptflow-azure 1.11.0 promptflow-core 1.11.0 promptflow-devkit 1.11.0 promptflow-tools 1.4.0 promptflow-tracing 1.11.0 langchain-openai 0.1.7

Please try the latest version 1.12.0, which was release on Jun 11.
