### ISSUE TITLE
[BUG] SSE streaming endpoint is not producing smooth event stream.

### ISSUE THREAD

**Issue by VeliKivilahti** [microsoft/promptflow#1090] opened 2023-11-10 09:07 UTC
**Describe the bug**
After deployment of the flow with docker or azure machine learning endpoint, consuming the event flow with "Accept: text/event-stream" header to get the response with SSE produces unsmooth response timings. The endpoint sends the messages in chunks each ~3 seconds instead of sending them whenever message is ready to send (or in smaller delay). This leads to each chunk having ~20 messages.

**How To Reproduce the bug**
Create a chat flow with the template (used GPT-4 for slower responses)
Deploy the flow using docker /or Azure machine learning endpoint
Consume the endpoint using curl or fetch-event-source npm package
Observe the unsmooth SSE stream

**Expected behavior**
Server would send SSE smoothly, acting close to both testing locally in interactive mode, and testing the endpoint in azure machine learning. 

 
**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b8
 - Operating System: Windows 10
 - Python Version using `python --version`: Python 3.11.6

**Additional context**
Tested with both with local deployment of docker and using azure machine learning endpoint. Tested consuming the event-stream with both curl and fetch-event-source npm package.

Interestingly testing the endpoint in azure machine learning studio does not show this behavior, but consuming the endpoint does.  (Might be handled by the frontend)

**Comment by zzn2** [comment] 2023-11-14 12:27
Hello @VeliKivilahti, thank you for contacting us. We sincerely apologize for any inconvenience caused.

We suppose that your chat flow could be using Azure OpenAI connections.

Upon examining the details and conducting several tests, we observed that Promptflow consistently dispatches events whenever data becomes available. This is primarily due to the Azure OpenAI service delivering tokens in chunks.

We will escalate this matter to the Azure OpenAI team for deeper insights.

In the interim, it may be feasible to implement some smoothing logic on the client side to alleviate the issue. Please refer to this [demo chat app](https://github.com/microsoft/promptflow/blob/2499daf7d3dd3c885e883811508ada1a2dd31d47/docs/media/how-to-guides/how-to-enable-streaming-mode/scripts/chat_app.py#L146C1-L146C1) as an example. It incorporates a brief 20ms pause between tokens to enhance the animation effect.

**Comment by VeliKivilahti** [comment] 2023-11-14 12:51
Thank you for the information, you were right about it being a Azure Open AI connection (forgot to disclose in the report). Wanted to know if it is a bug or a feature on the prompt flow side before starting experimenting on the client side smoothing. You can close the issue if you want to, or update this when / if you get some more insights from AOAI team as the issue is not strictly related to this repo.

**Comment by zzn2** [comment] 2023-11-15 07:25
Thanks. Seeing as PromptFlow always triggers events when data is ready, the problem isn't associated with PromptFlow. We plan to close this issue at this point. Once we receive additional information from the Azure OpenAI team, we will provide updates here.

**Closed by zzn2** 2023-11-15 07:25 UTC
Labels: bug
