### ISSUE TITLE
[BUG] pf: error: unrecognized arguments: --user-agent prompt-flow-extension/1.6.0

### ISSUE THREAD

**Issue by paulshealy1** [microsoft/promptflow#1456] opened 2023-12-11 18:06 UTC
**Describe the bug**

C:\Users\paulsh\Documents\promptflow-samples-ozguler\sample_gallery\evaluate_semantic_kernel_planner\python_evalution\promptflow_evaluation>C:\Users\paulsh\AppData\Local\miniconda3\envs\promptflow-samples-ozguler\python.exe -m promptflow._cli._pf.entry flow test --flow c:\Users\paulsh\Documents\promptflow-samples-ozguler\sample_gallery\evaluate_semantic_kernel_planner\python_evalution\promptflow_evaluation --user-agent "prompt-flow-extension/1.6.0 (win32; x64) VSCode/1.84.2"
usage: pf [-h] [-v] {flow,connection,run,config,tool} ...
pf: error: unrecognized arguments: --user-agent prompt-flow-extension/1.6.0 (win32; x64) VSCode/1.84.2

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Using the latest PF CLI and VS Code extension, run a flow.

**Comment by ttthree** [comment] 2023-12-12 08:59
Could you please share your prompt flow sdk cli version?

```
pf -v
```

**Comment by D-W-** [comment] 2023-12-12 09:48
Hi @paulshealy1 , the issue is caused because unmatched version between VS Code extension and SDK/CLI. Could you upgrade promptflow SDK under environment "promptflow-samples-ozguler" to >= 1.1.0? 

```cmd
pip install promptflow>=1.1.0
```

**Comment by spygi** [comment] 2023-12-12 18:59
Installing the latest promptflow 1.1.1 worked for me.

Just mentioning for others, another workaround would be to manually run `pf flow test --flow flow_file` (without the offending --user-agent argument)

**Comment by paulshealy1** [comment] 2023-12-12 19:07
```
(promptflow-samples-ozguler) C:\Users\paulsh\Documents\promptflow-samples-ozguler\sample_gallery\evaluate_semantic_kernel_planner\python_evalution\promptflow_evaluation>pf -v
promptflow                       1.1.1

Executable 'C:\Users\paulsh\AppData\Local\anaconda3\python.exe'
Python (Windows) 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
```

@ttthree, @D-W-, @spygi, I think there is an issue activating the right environment when running from the extension. I'm happy to hop on a call with one of you to debug.

**Comment by D-W-** [comment] 2023-12-13 03:19
Offline syncing, the issue seems because mixed usage with miniconda and anaconda.

**Comment by D-W-** [comment] 2023-12-14 03:25
Hi @paulshealy1 , I'm closing this since it's a local environment issue. Feel free to reopen if there's still issue.

**Closed by D-W-** 2023-12-14 03:25 UTC
Labels: bug
