### ISSUE TITLE
[BUG] [VSCode Extension] pf: error: unrecognized arguments: (win32; x64) VSCode/1.85.1"

### ISSUE THREAD

**Issue by Wix97** [microsoft/promptflow#1745] opened 2024-01-15 07:26 UTC
**Describe the bug**
[A clear and concise description of the bug.](pf: error: unrecognized arguments: (win32; x64) VSCode/1.85.1")
<img width="714" alt="image" src="https://github.com/microsoft/promptflow/assets/103412028/4d39bd6c-fed9-4179-8a12-21cdb1179873">

**How To Reproduce the bug**
1. Setup a flow
2. Setup a test suite yaml file for the flow
3. Trigger the flow by clicking the green button
<img width="127" alt="image" src="https://github.com/microsoft/promptflow/assets/103412028/8613a697-9005-4a23-a69c-bd1cfcb0f306">

**Environment Information**
 - Promptflow Package Version using `pf -v`: 1.3.0
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.9.18
 - Prompt Flow extension version. 1.9.0

**Comment by JYC-99** [comment] 2024-01-16 01:01
@Wix97 can you help paste the command which triggered this error in the terminal?

**Comment by Wix97** [comment] 2024-01-16 13:23
I triggered the bug via UI. Here is the output of 'Test Results' tab.
![image](https://github.com/microsoft/promptflow/assets/103412028/95c5d30b-8b96-4609-b461-67137c5e79a0)
There is no more helpful outputs in other tabs.

**Comment by Joouis** [comment] 2024-01-18 03:50
@Wix97 Thanks for your supports and patience. We've figured out the root cause and the issue will be fixed in next release. You can click "Run" to execute batch run directly under `xxx_batch_run_create.yaml` file as a workaround.

![Screenshot 2024-01-18 114808](https://github.com/microsoft/promptflow/assets/8896124/49c5fe9a-aa30-4373-a16d-2552bb2a4a90)

**Closed** 2024-02-24 21:32 UTC
Labels: bug, no-recent-activity
