### ISSUE TITLE
[BUG] Running out of time (timeout 60 seconds)

### ISSUE THREAD

**Issue by Sendery** [microsoft/promptflow#987] opened 2023-11-03 13:01 UTC
**Describe the bug**
I do run out of time when using a tool (more than 60 secs)

**How To Reproduce the bug**
Create a tool in python so it consume more than 60 seconds

**Expected behavior**
I will want to be able to set some where in the proyecto or at a level tool the timeout for a flow or a tool.

**Additional context**
I found out in the documentatino of the [prompt executor](https://microsoft.github.io/promptflow/reference/python-library-reference/promptflow.executor.html?highlight=line_timeout) that there is a line_timeout param but I dont know how to set it up from the vscode extension/or config file use form my project

**Comment by thy09** [comment] 2023-11-06 01:41
Hi @Sendery 
Could you explain more about your scenario? 
Are you hitting the same issue with this: https://github.com/microsoft/promptflow/issues/690

**Comment by Sendery** [comment] 2023-11-07 16:21
I did look at the issue #690, but for me it happened when executing a python "tool" that consumes more than 60 seconds during it computation time  in the vscode extension, and the error is reported is in the output of the terminal

**Comment by thy09** [comment] 2023-11-09 07:55
Hi @Sendery We didn't set a tool level 60 seconds timeout.
Do you mean that you see this log?
"WARNING  echo in line 0 has been running for 60 seconds"
It is just system log to hint user that the tool runs for a long time, the node is still running and it will not be cancelled.

**Comment by thy09** [comment] 2023-12-11 07:53
Close this issue since no further feedback, feel free to reactivate it if the issue is observed again.

**Closed by thy09** 2023-12-11 07:53 UTC
Labels: bug, no-recent-activity
