### ISSUE TITLE
[BUG] [VSCode Extension] Batch Run Visualization shows 'Without import data'

### ISSUE THREAD

**Issue by Wix97** [microsoft/promptflow#1516] opened 2023-12-18 14:16 UTC
**Describe the bug**
<img width="763" alt="image" src="https://github.com/microsoft/promptflow/assets/103412028/2a3f0a9c-222e-4c09-8b21-e102ad807e6e">
Batch run visualization sometimes shows 'Without Import Data'

**How To Reproduce the bug**
Trigger the batch run of a flow, and trigger another flow with run against run, the bug may occur.

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
2. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: promptflow 1.2.0 promptflow-tools  1.0.1
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.9.18
 - VS Code version: 1.85.1
 - Prompt Flow extension version 1.7.0

**Comment by Wix97** [comment] 2023-12-18 14:17
Please feel free to ping me via teams

**Comment by zhengfeiwang** [comment] 2023-12-26 03:54
Hi @Wix97 , thanks for your feedback! As your internal sync with Kaiyi, there might be `NaN` in the flow output - this should be the root cause of your "Without Import Data" error: during the visualize operation, Python SDK will dump the run info to a JSON string and pass to JavaScript to render, however, `NaN` is not a valid value in JSON, so JavaScript cannot parse it successfully.

We will have some discussion how to deal with the `NaN` value during the process, and it needs some time as many of us are OOF these days. However, I think maybe you can try not outputing `NaN` as a workaround - another concrete value or `None` should be good, if it is possible for you, so that Python SDK can dump a valid JSON string for JavaScript to parse and render.

Please let me know if the above solution works for you, and I will keep you updated with the progress. Let's use this item to track this bug.

cc. @RealKai42

**Comment by Wix97** [comment] 2023-12-26 12:05
Thanks for the update @zhengfeiwang ! It looks like I guessed the cause of the bug correctly, we have adjusted the code to avoid printing nan in the output and the bug is not triggered any more. Looking forward to seeing bug fixes.

**Comment by zhengfeiwang** [comment] 2024-01-23 03:22
Hi @Wix97 , `promptflow==1.4.0` is released yesterday: <https://pypi.org/project/promptflow/1.4.0/>, which carries this related fix. Please have a try and let me know if you still run into same issue.

**Comment by zhengfeiwang** [comment] 2024-01-23 03:23
I will close this issue for now, and feel free to re-open it.

**Closed by zhengfeiwang** 2024-01-23 03:23 UTC
Labels: bug
